export const sectors = [
  "Administración de empresas",
  "Administración Pública",
  "Agricultura y ganadería",
  "Atención a clientes",
  "Calidad, producción e I+D",
  "Comercial y ventas",
  "Compras, logística y almacén",
  "Diseño y artes gráficas",
  "Educación y formación",
  "Finanzas y banca",
  "Informática y telecomunicaciones",
  "Ingenieros y técnicos",
  "Inmobiliario y construcción",
  "Legal",
  "Marketing y comunicación",
  "Otros",
  "Profesiones, artes y oficios",
  "Recursos humanos",
  "Sanidad y salud",
  "Sector Farmacéutico",
  "Turismo y restauración",
  "Ventas al detalle",
];
